# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: CI Hadoop 2

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        codes: [ 'uncompressed,brotli', 'gzip,snappy' ]
    name: Build Parquet with JDK ${{ matrix.java }} and ${{ matrix.codes }}

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: before_install
        env:
          CI_TARGET_BRANCH: $GITHUB_HEAD_REF
        run: |
          bash dev/ci-before_install.sh
      - name: install
        run: |
          EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs -q -DforceStdout)
          export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"
          mvn install --batch-mode -P hadoop2 -DskipTests=true -Dmaven.javadoc.skip=true -Dsource.skip=true -Djava.version=1.8
      - name: verify
        env:
          TEST_CODECS: ${{ matrix.codes }}
          JAVA_VERSION: ${{ matrix.java }}
        run: |
          EXTRA_JAVA_TEST_ARGS=$(mvn help:evaluate -Dexpression=extraJavaTestArgs -q -DforceStdout)
          export MAVEN_OPTS="$MAVEN_OPTS $EXTRA_JAVA_TEST_ARGS"
          mvn verify --batch-mode -P hadoop2 javadoc:javadoc -Pci-test
